#!/bin/bash

#This script will prompt the installer for the key information related to each specific terminal

#variables for the config files to modify/create
PUPPET_CONF=/etc/puppet/puppet.conf
FACTS_CONF=/etc/facter/facts.d/pos.txt
mkdir -p /etc/facter/facts.d

#define global variables
puppet_master=""
geo_location=""
store_number=""

#####################################################
# Helper function to prompt for user input and      #
# sets the provided variable with the value entered #
#####################################################
promptForValue() {

  read -p "$1": userResponse

  local  __valueVar=$2
  local  value=$userResponse
  if [[ "$__valueVar" ]]; then
     eval $__valueVar="$value"
  else
     echo "$value"
  fi
}

#####################################################
# Main function to prompt for values for config(s)  #
#####################################################
setupQuestions() {
  echo "========= PayPal Puppet Agent Setup ========="
  promptForValue "Please enter the PUPPET MASTER HOSTNAME" __puppet_master
  promptForValue "Please enter the GEO LOCATION CODE" __geo_location
  promptForValue "Please enter the STORE NUMBER" __store_number

  echo ""
  echo "You entered:"
  printf "%-25s %s\n" "PUPPET MASTER HOSTNAME:" $__puppet_master
  printf "%-25s %s\n" "GEO LOCATION CODE:" $__geo_location
  printf "%-25s %s\n" "STORE_NUMBER:" $__store_number
  echo ""

  #set the global variable values
  puppet_master=$__puppet_master
  geo_location=$__geo_location
  store_number=$__store_number
}


#execute the main function until the user is satisfied
while [ true ]
do
  #execute the main function
  setupQuestions

  read -p "Are these values correct? (y|n): " choice
  case "$choice" in 
    y|Y ) break;;
    * ) echo "Please try again...";;
  esac
done

#set the puppet.conf content
echo '#Generated by paypal-puppet-master-setup.sh' > $PUPPET_CONF
echo '[main]' >> $PUPPET_CONF
echo '   logdir = /var/log/puppet' >> $PUPPET_CONF
echo '   rundir = /var/run/puppet' >> $PUPPET_CONF
echo '   ssldir = $vardir/ssl' >> $PUPPET_CONF
echo '[master]' >> $PUPPET_CONF
echo "   certname = $HOSTNAME" >> $PUPPET_CONF
echo '   autosign = true' >> $PUPPET_CONF
echo '   reports = store, http' >> $PUPPET_CONF
echo '   reporturl = http://192.168.1.5:3000/reports/upload' >> $PUPPET_CONF
echo '[agent]' >> $PUPPET_CONF
echo '   classfile = $vardir/classes.txt' >> $PUPPET_CONF
echo '   localconfig = $vardir/localconfig' >> $PUPPET_CONF
echo "   server = $puppet_master" >> $PUPPET_CONF
echo '   runinterval = 1m' >> $PUPPET_CONF
echo '   pluginsync = true' >> $PUPPET_CONF
echo '   report = true' >> $PUPPET_CONF
echo "Puppet configuration file created at $PUPPET_CONF"
cat $PUPPET_CONF
echo "-------------------------------------------------"

#set the pos.txt FACTS file
echo "geo_location=$geo_location" > $FACTS_CONF
echo "store_number=$store_number" >> $FACTS_CONF
echo "Custom Facter facts file created at $FACTS_CONF"
cat $FACTS_CONF
echo "-------------------------------------------------"

#Start the services and set to start on boot
sudo service puppetmaster start
sudo service puppet start
sudo chkconfig puppetmaster on
sudo chkconfig puppet on

sleep 10
echo "Testing Puppet Agent connection to server..."
sudo puppet agent --test


